# Generated by Django 3.0.8 on 2021-06-06 21:02

import datetime
import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)),
                ('name', models.TextField(max_length=64)),
                ('description', models.TextField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)),
                ('date', models.DateField(unique=True)),
                ('select_by_time', models.TimeField(default=datetime.time(15, 0))),
                ('meal_options', models.ManyToManyField(related_name='menus', to='menu.MealOption')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)),
                ('employee', models.TextField(max_length=64)),
                ('note', models.TextField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.MealOption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('menu', 'employee'), name='unique_meal'),
        ),
    ]
