# Generated by Django 3.0.8 on 2021-06-07 00:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='YYYY-MM-DD', unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='select_by_time',
            field=models.TimeField(default=datetime.time(11, 0), help_text='Up to what time can employees register their meal choice? (HH:MM:SS)'),
        ),
    ]
